[project]
name = "engineering-board-dev-tools"
version = "0.0.0"
requires-python = "==3.14.7"
dependencies = [
  "actionlint-py==1.7.12.24",
  "check-jsonschema==0.38.0",
  "coverage==7.15.4",
  "cyclonedx-bom==7.3.1",
  "mypy==2.3.1",
  "pip-audit==2.10.1",
  "pre-commit==4.6.2",
  "pytest==9.1.1",
  "radon==6.0.1",
  "ruff==0.16.3",
  "shellcheck-py==0.11.0.1",
  "shfmt-py==3.13.0.3",
  "vulture==2.16",
  "yamllint==1.38.0",
  "zizmor==1.29.0",
]
