#!/usr/bin/env bash
# tests/scratch/append.sh — deterministic coverage for board-scratch-append.sh.
#
# board-scratch-append.sh exists to make scratch-append fidelity structural
# rather than LLM-best-effort (issue #3). This battery pins the guarantees the
# Stop procedure's step (d) now depends on:
#
#   - A finding whose evidence_quote contains shell-hostile characters
#     (%s, backslashes, "smart"/escaped quotes, $VARS, backticks, single quotes)
#     survives the write byte-for-byte at the JSON value level.
#   - The timestamp comment is generated by the script (deterministic via an
#     EB_SCRATCH_APPEND_NOW override) — the model never types it.
#   - Repeated appends accumulate; they never clobber the prior object, and the
#     concatenated objects stay parseable by the consolidator's scanner.
#   - A malformed / truncated / empty copy fails LOUDLY (non-zero exit) and
#     writes nothing — the silent-data-loss path is closed.
#   - A valid object wrapped in stray prose is salvaged exactly as the
#     consolidator would have salvaged it.
#   - END-TO-END: a finding written by the script, whose quote is hostile to
#     shell string-formatting, anchors against the transcript and PROMOTES under
#     board-consolidate.sh — the exact path that previously deferred when the
#     orchestrator hand-wrote scratch via printf.
#
# Usage:
#   bash tests/scratch/append.sh                # auto-detect plugin root
#   bash tests/scratch/append.sh <plugin-root>  # explicit root
#
# Exits 0 iff every assertion passes.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEFAULT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PLUGIN_ROOT="${1:-$DEFAULT_ROOT}"

APPEND="$PLUGIN_ROOT/hooks/scripts/board-scratch-append.sh"
CONSOLIDATE="$PLUGIN_ROOT/hooks/scripts/board-consolidate.sh"

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 not on PATH — required by board-scratch-append.sh" >&2
  exit 1
fi

TMP="$(python3 -c 'import tempfile; print(tempfile.mkdtemp(prefix="eb-scratch-").replace(chr(92), "/"))')"
cleanup() { rm -rf "$TMP" 2>/dev/null || true; }
trap cleanup EXIT

PASS=0
FAIL=0
report() {
  if [ "$1" = "0" ]; then
    printf "  [PASS] %s\n" "$2"; PASS=$((PASS + 1))
  else
    printf "  [FAIL] %s%s\n" "$2" "${3:+ -- $3}"; FAIL=$((FAIL + 1))
  fi
}

# Read findings[<idx>].<field> out of a scratch file using the SAME raw_decode
# scan the consolidator/auditor use — proves round-trip against the real reader.
scratch_field() {
  local file="$1" idx="$2" field="$3"
  python3 - "$file" "$idx" "$field" <<'PY'
import sys, json
path, idx, field = sys.argv[1], int(sys.argv[2]), sys.argv[3]
text = open(path, encoding="utf-8", errors="replace").read()
dec = json.JSONDecoder()
findings = []
i, n = 0, len(text)
while i < n:
    if text[i] == "{":
        try:
            obj, end = dec.raw_decode(text[i:])
            for f in (obj.get("findings") or []):
                findings.append(f)
            i += end; continue
        except Exception:
            pass
    i += 1
try:
    sys.stdout.write(str(findings[idx].get(field, "")))
except Exception:
    sys.stdout.write("<MISSING>")
PY
}

count_objects() {  # number of top-level JSON objects in a scratch file
  python3 - "$1" <<'PY'
import sys, json
text = open(sys.argv[1], encoding="utf-8", errors="replace").read()
dec = json.JSONDecoder()
c, i, n = 0, 0, len(text)
while i < n:
    if text[i] == "{":
        try:
            _, end = dec.raw_decode(text[i:]); c += 1; i += end; continue
        except Exception:
            pass
    i += 1
print(c)
PY
}

# A quote engineered to be hostile to naive shell string-formatting yet valid as
# a JSON string value. If any of these survive a printf/echo hop intact it is by
# luck; through the script they must survive deterministically.
HOSTILE_QUOTE='render() mishandles printf("%s", $HOME) and '\''single'\'' \backslash `ticks`'

# ── 1. Script exists and is executable ──────────────────────────────────────
if [ -x "$APPEND" ]; then
  report 0 "board-scratch-append.sh exists and is executable"
else
  report 1 "board-scratch-append.sh exists and is executable" "not found/executable: $APPEND"
  echo ""; echo "scratch-append: $PASS pass, $FAIL fail"; exit 1
fi

# ── 2-4. Happy path: exit 0, file created, timestamp pinned, quote round-trips ─
UNIT="$TMP/unit"
mkdir -p "$UNIT"
SCRATCH1="$UNIT/nested/dir/session-a.md"   # nested dir must be auto-created
FINDING1="$UNIT/finding1.json"
python3 - "$FINDING1" "$HOSTILE_QUOTE" <<'PY'
import sys, json
path, quote = sys.argv[1], sys.argv[2]
obj = {"schema_version": "0.2.1", "findings": [{
    "scratch_id": "S-unit-1", "type": "bug", "confidence": "confirmed",
    "title": "render helper mishandles format and env expansion",
    "affects": "scratch/render", "evidence_quote": quote,
    "discovered": "2026-06-01", "tags": ["render"],
    "schema_validation_result": "accept"}]}
open(path, "w", encoding="utf-8").write(json.dumps(obj, ensure_ascii=False))
PY

if EB_SCRATCH_APPEND_NOW="2026-06-01T12:34:56Z" bash "$APPEND" "$SCRATCH1" < "$FINDING1" > "$UNIT/out1" 2> "$UNIT/err1"; then
  report 0 "happy path exits 0"
else
  report 1 "happy path exits 0" "stderr=$(tr '\n' ' ' < "$UNIT/err1")"
fi

if [ -f "$SCRATCH1" ]; then
  report 0 "scratch file created (parent dirs auto-made)"
else
  report 1 "scratch file created (parent dirs auto-made)" "missing: $SCRATCH1"
fi

if grep -qF "<!-- 2026-06-01T12:34:56Z -->" "$SCRATCH1"; then
  report 0 "timestamp comment generated by script (override pinned exactly)"
else
  report 1 "timestamp comment generated by script" "no pinned comment line in scratch"
fi

GOT_QUOTE="$(scratch_field "$SCRATCH1" 0 evidence_quote)"
if [ "$GOT_QUOTE" = "$HOSTILE_QUOTE" ]; then
  report 0 "shell-hostile evidence_quote round-trips byte-for-byte"
else
  report 1 "shell-hostile evidence_quote round-trips" "want [$HOSTILE_QUOTE] got [$GOT_QUOTE]"
fi

# ── B005: a human capture summary is printed on stdout (visible on the turn) ──
if grep -qF 'EB-CAPTURE-SUMMARY: captured 1 finding(s):' "$UNIT/out1" \
   && grep -qF 'render helper mishandles format and env expansion' "$UNIT/out1" \
   && grep -qF '/pm-start' "$UNIT/out1"; then
  report 0 "B005: capture summary line names the finding + /pm-start"
else
  report 1 "B005: capture summary line present" "out1=$(tr '\n' '|' < "$UNIT/out1")"
fi

# ── 5. Append accumulates, never clobbers ───────────────────────────────────
FINDING2="$UNIT/finding2.json"
printf '%s' '{"schema_version":"0.2.1","findings":[{"scratch_id":"S-unit-2","type":"observation","confidence":"tentative","title":"second finding","affects":null,"evidence_quote":"a second one","discovered":"2026-06-01","tags":[]}]}' > "$FINDING2"
EB_SCRATCH_APPEND_NOW="2026-06-01T12:35:00Z" bash "$APPEND" "$SCRATCH1" < "$FINDING2" > /dev/null 2> "$UNIT/err2" || true
OBJ_COUNT="$(count_objects "$SCRATCH1")"
FIRST_STILL="$(scratch_field "$SCRATCH1" 0 scratch_id)"
SECOND_NEW="$(scratch_field "$SCRATCH1" 1 scratch_id)"
if [ "$OBJ_COUNT" = "2" ] && [ "$FIRST_STILL" = "S-unit-1" ] && [ "$SECOND_NEW" = "S-unit-2" ]; then
  report 0 "second append accumulates (both objects parseable, first preserved)"
else
  report 1 "second append accumulates" "objs=$OBJ_COUNT first=$FIRST_STILL second=$SECOND_NEW"
fi

# ── 6. Zero-findings object is valid and accepted ───────────────────────────
SCRATCH_EMPTY="$UNIT/session-empty.md"
if printf '%s' '{"schema_version":"0.2.1","findings":[]}' | bash "$APPEND" "$SCRATCH_EMPTY" > /dev/null 2> "$UNIT/err_empty"; then
  report 0 "zero-findings object accepted (exit 0)"
else
  report 1 "zero-findings object accepted" "stderr=$(tr '\n' ' ' < "$UNIT/err_empty")"
fi

# ── 7. Empty stdin fails loudly (exit 3), writes nothing ────────────────────
SCRATCH_NONE="$UNIT/never-created-empty.md"
set +e
printf '' | bash "$APPEND" "$SCRATCH_NONE" > /dev/null 2> "$UNIT/err_e"
RC=$?
set -e
if [ "$RC" -eq 3 ] && [ ! -f "$SCRATCH_NONE" ]; then
  report 0 "empty stdin -> exit 3 and no file written"
else
  report 1 "empty stdin -> exit 3 and no file written" "rc=$RC file_exists=$([ -f "$SCRATCH_NONE" ] && echo yes || echo no)"
fi

# ── 8. Truncated / invalid JSON fails loudly (exit 3), writes nothing ───────
SCRATCH_BAD="$UNIT/never-created-bad.md"
set +e
printf '%s' '{"schema_version":"0.2.1","findings":[ {"scratch_id":"S-x","title":"oops"' | bash "$APPEND" "$SCRATCH_BAD" > /dev/null 2> "$UNIT/err_bad"
RC=$?
set -e
if [ "$RC" -eq 3 ] && [ ! -f "$SCRATCH_BAD" ]; then
  report 0 "truncated JSON -> exit 3 and no file written (silent-loss path closed)"
else
  report 1 "truncated JSON -> exit 3 and no file written" "rc=$RC file_exists=$([ -f "$SCRATCH_BAD" ] && echo yes || echo no)"
fi

# ── 8b. Object present but missing 'findings' array -> exit 3 ────────────────
set +e
printf '%s' '{"schema_version":"0.2.1","oops":[]}' | bash "$APPEND" "$UNIT/never-created-noarr.md" > /dev/null 2> "$UNIT/err_noarr"
RC=$?
set -e
if [ "$RC" -eq 3 ]; then
  report 0 "object without 'findings' array -> exit 3 (contract enforced)"
else
  report 1 "object without 'findings' array -> exit 3" "rc=$RC"
fi

# ── 9. Salvage: valid object wrapped in stray prose/fence -> exit 0 ──────────
SCRATCH_SALV="$UNIT/session-salvage.md"
set +e
printf '%s\n' 'Here is the result:' '```json' '{"schema_version":"0.2.1","findings":[{"scratch_id":"S-salv","type":"bug","confidence":"confirmed","title":"t","affects":null,"evidence_quote":"q","discovered":"2026-06-01","tags":[]}]}' '```' | bash "$APPEND" "$SCRATCH_SALV" > "$UNIT/out_salv" 2> "$UNIT/err_salv"
RC=$?
set -e
SALV_ID="$(scratch_field "$SCRATCH_SALV" 0 scratch_id)"
if [ "$RC" -eq 0 ] && [ "$SALV_ID" = "S-salv" ] && grep -q "salvaged_via_rawdecode" "$UNIT/out_salv"; then
  report 0 "prose-wrapped object salvaged exactly as the consolidator would (exit 0)"
else
  report 1 "prose-wrapped object salvaged" "rc=$RC id=$SALV_ID out=$(tr '\n' ' ' < "$UNIT/out_salv")"
fi

# ── 10. Usage error: missing scratch-path arg -> exit 1 ─────────────────────
set +e
printf '%s' '{"schema_version":"0.2.1","findings":[]}' | bash "$APPEND" > /dev/null 2> "$UNIT/err_usage"
RC=$?
set -e
if [ "$RC" -eq 1 ]; then
  report 0 "missing scratch-path arg -> exit 1 (usage)"
else
  report 1 "missing scratch-path arg -> exit 1" "rc=$RC"
fi

# ── 11. END-TO-END: script-written hostile quote PROMOTES under consolidate ──
# This is the assertion that maps directly to issue #3: a faithful scratch write
# lets a quote with shell-hostile characters anchor against the transcript and
# promote, where the old printf/echo hand-copy would have mangled it and the
# consolidator would have logged deferred_anchor_unmatched.
PROJECT="$TMP/project"
BOARD_DIR="$PROJECT/engineering-board/scratch"
mkdir -p "$BOARD_DIR/bugs" "$BOARD_DIR/features" "$BOARD_DIR/questions" \
         "$BOARD_DIR/observations" "$BOARD_DIR/_sessions" "$PROJECT/.engineering-board"

cat > "$PROJECT/engineering-board/BOARD-ROUTER.md" <<'EOF'
# Board Router

| project | path | affects prefix |
|---------|------|----------------|
| scratch | engineering-board/scratch/ | scratch/ |
EOF
printf '# scratch - Board\n\n## Open\n\n' > "$BOARD_DIR/BOARD.md"

TRANSCRIPT="$PROJECT/transcript.jsonl"
E2E_FINDING="$TMP/e2e-finding.json"
# Author transcript + finding together so the assistant text provably CONTAINS
# the finding's evidence_quote as a substring (nested Claude Code schema).
python3 - "$TRANSCRIPT" "$E2E_FINDING" "$HOSTILE_QUOTE" <<'PY'
import sys, json
transcript, finding_path, quote = sys.argv[1], sys.argv[2], sys.argv[3]
assistant_text = "Investigated the formatter: " + quote + " — confirmed by the failing repro."
lines = [
    {"role": "user", "content": "the render helper looks broken, can you confirm"},
    {"type": "assistant", "message": {"role": "assistant",
        "content": [{"type": "text", "text": assistant_text}]}},
]
with open(transcript, "w", encoding="utf-8") as f:
    for o in lines:
        f.write(json.dumps(o, ensure_ascii=False) + "\n")
obj = {"schema_version": "0.2.1", "findings": [{
    "scratch_id": "S-e2e-1", "type": "bug", "confidence": "confirmed",
    "title": "render helper mishandles printf format and env expansion",
    "affects": "scratch/render", "evidence_quote": quote,
    "discovered": "2026-06-01", "tags": [],
    "schema_validation_result": "accept"}]}
open(finding_path, "w", encoding="utf-8").write(json.dumps(obj, ensure_ascii=False))
PY

cat > "$PROJECT/.engineering-board/last-stop-stdin.json" <<EOF
{"session_id":"e2e-session","transcript_path":"$TRANSCRIPT","hook_event_name":"Stop","stop_hook_active":false}
EOF

# Write scratch via the helper (the production path), then consolidate.
if bash "$APPEND" "$BOARD_DIR/_sessions/e2e-session.md" < "$E2E_FINDING" > /dev/null 2> "$UNIT/err_e2e"; then
  export CLAUDE_PROJECT_DIR="$PROJECT"
  bash "$CONSOLIDATE" < "$PROJECT/.engineering-board/last-stop-stdin.json" > "$UNIT/cons.out" 2> "$UNIT/cons.err" || true
  DISP="$(python3 - "$BOARD_DIR/consolidation.log" <<'PY'
import sys, json
hit = ""
try:
    for line in open(sys.argv[1], encoding="utf-8", errors="replace"):
        line = line.strip()
        if not line:
            continue
        try:
            r = json.loads(line)
        except Exception:
            continue
        if r.get("scratch_id") == "S-e2e-1":
            hit = r.get("disposition", ""); break
except Exception:
    pass
print(hit)
PY
)"
  case "$DISP" in
    promoted_*) report 0 "end-to-end: hostile-quote finding PROMOTES via consolidate ($DISP)" ;;
    *)          report 1 "end-to-end: hostile-quote finding PROMOTES via consolidate" "disposition='${DISP:-<none>}' (expected promoted_*)" ;;
  esac
else
  report 1 "end-to-end: scratch-append wrote the e2e finding" "stderr=$(tr '\n' ' ' < "$UNIT/err_e2e")"
fi

echo ""
echo "================================================================"
echo "SCRATCH-APPEND SUMMARY: $PASS pass, $FAIL fail"
echo "================================================================"
if [ "$FAIL" -ne 0 ]; then
  exit 1
fi
exit 0
